### ISSUE TITLE
 Not work on Angular2 ^3.0.0

### ISSUE THREAD

**Issue by SadovovAlex** [simon-void/pikaday_datepicker_angular2#1]
Not work on Angular2 ^3.0.0 or not upgraded?

**Comment by simon-void** [comment]
Hi Alex,

i will provide an upgrade this week (probably on friday).

Regards,

Stephan

 

Gesendet: Mittwoch, 17. Mai 2017 um 11:17 Uhr
Von: Alex <notifications@github.com>
An: simon-void/pikaday_datepicker_angular2 <pikaday_datepicker_angular2@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [simon-void/pikaday_datepicker_angular2] Not work on Angular2 ^3.0.0 (#1)


Not work on Angular2 ^3.0.0 or not upgraded?

**Comment by simon-void** [comment]
hi Alex,

 

i upgraded pikaday_datepicker_angular2 to version 2.0.0, it now uses Angular2 ^3.0.0

https://pub.dartlang.org/packages/pikaday_datepicker_angular2

 

regards,

Stephan

 

Gesendet: Mittwoch, 17. Mai 2017 um 11:17 Uhr
Von: Alex <notifications@github.com>
An: simon-void/pikaday_datepicker_angular2 <pikaday_datepicker_angular2@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [simon-void/pikaday_datepicker_angular2] Not work on Angular2 ^3.0.0 (#1)


Not work on Angular2 ^3.0.0 or not upgraded?

**Comment by SadovovAlex** [comment]
Thank you very much. i will test it next week.

**Comment by SadovovAlex** [comment]
nice work, thank you!
