### ISSUE TITLE
self.getPikadayMillisecondsSinceEpoch is not a function

### ISSUE THREAD

**Issue by SadovovAlex** [simon-void/pikaday_datepicker_angular2#4]
Hi

not set clicked date to pikaday component in a chrome after deploy webserver
but work fine in a chromium on my local pc
if i clicked on day in console found error:

Uncaught TypeError: self.getPikadayMillisecondsSinceEpoch is not a function
    at DC.dart.DC.$1 (main.dart.js:25409)
    at Object.ot (main.dart.js:1814)
    at dart.K_ (main.dart.js:9848)
    at Pikaday.<anonymous> (main.dart.js:9844)
    at Pikaday.setDate (pikaday.js:788)
    at HTMLDivElement.Pikaday.self._onMouseDown (pikaday.js:447)

Line 447 = self.setDate(new Date(target.getAttribute('data-pika-year'), target.getAttribute('data-pika-month'), target.getAttribute('data-pika-day')));

![image](https://user-images.githubusercontent.com/14030285/27475940-90055d30-580f-11e7-97f5-8e0cd81bb43c.png)

pubspec:

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  swagger:
    path: lib/swagger
  angular2: ^3.1.0
  angular2_components: ^0.5.0
  validator: any
  bootstrap: 3.3.7
  pikaday_datepicker_angular2: "^2.1.4"
  http: "^0.11.3+13"
  jsonp: any
  json_object: 1.0.19+1
  dart_config: any
  #validator: ">=0.0.4 <0.1.0"
  logging: any

dev_dependencies:
  browser: ^0.10.0
  angular_test: ^1.0.0-beta+2
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
  dartson: "^0.2.7"

transformers:
- angular2:
    platform_directives:
#    - 'package:angular2/common.dart#CORE_DIRECTIVES'
#    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart

**Comment by SadovovAlex** [comment]
and not set value on [(day)]

> <pikaday cssClasses="form-control input-sm" [(day)]="DateFrom" format="DD-MM-YYYY" (change)="myCheckUserInput()"
>                                              minDate="2017-01-01" maxDate="2025-12-31"
>                                              firstDay="1">
>   </pikaday>
> 
> ngOnInit() async {
>     //создаем элемент календаря
>     DateTime today = new DateTime.now();
>     DateFrom = new DateTime(today.year, today.month, 1);
> 
>     DateTo = new DateTime.now().toUtc();
> 

`

**Comment by SadovovAlex** [comment]
i found info on the page =)
https://pub.dartlang.org/packages/pikaday_datepicker_angular2

add to index.html
`<script src="packages/pikaday/pikaday_dart_helpers.js"></script>
`
work fine =) thx

**Comment by SadovovAlex** [comment]
No error on click date, but second promblem not solve
not set value on component on ngOnInit() 

```
ngOnInit() async {
    DateTime today = new DateTime.now();
    DateFrom = new DateTime(today.year, today.month, 1);
    DateTo = new DateTime.now().toUtc();
    print("DateTo="+DateTo.toString());
}
```
```

 <div class="col-sm-4">
                                    <label>Дата с:</label>
                                    <pikaday cssClasses="form-control input-sm" [(day)]="DateFrom" format="DD-MM-YYYY" (change)="myCheckUserInput()"
                                             minDate="2017-01-01" maxDate="2025-12-31"
                                             firstDay="1">
                                    </pikaday>

                                </div>
```

![image](https://user-images.githubusercontent.com/14030285/27477903-554ce6f2-5816-11e7-89f8-f11b159b4af2.png)

**Comment by simon-void** [comment]
This should be fixed by setting `showDayOnInit` to true:
```
<pikaday cssClasses="form-control input-sm" format="DD-MM-YYYY"
    [(day)]="DateFrom" (change)="myCheckUserInput()"
    minDate="2017-01-01" maxDate="2025-12-31" firstDay="1"
    showDayOnInit="true">
</pikaday>
```
I wonder, was the default value for `showDayOnInit=true` before i switched my pikaday-wrapper-lib?!?
I think it was, but i thought, it would be better to use as much default-behaviour as possible, but in that case, i should have adapted the documentation to reflect this (use showDayOnInit="true" in the example).
On the other hand, i already changed det variable name from defaultDate to showDayOnInit and this seems to be the expected behaviour. So i might make this the default after all. (Let me think about this. But set the value manually for now.)

**Comment by SadovovAlex** [comment]
ok, i set this variable to true and it is work perfect =)
thank you for your work

have a nice day
